name: ğŸš€ Build and Deploy Page

on:
  push:
    paths:
      - "portfolio/**"
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Code checkout
        uses: actions/checkout@v3

      - name: ğŸ—ï¸ Build the Docker image
        run: |
          docker build -t my-portfolio:latest -f portfolio/Dockerfile .

      - name: ğŸš€ Build the Docker image
        run: |
          docker run -p 3000:3000 my-portfolio:latest
